Dsproperties
cyberdudes-mf/rukoru pull request #23
Opened 2018-05-23 13:49 UTC by mizunaki

DS画面でプロパティを編集できるようにしました。

2018-05-23 15:14 UTC, willard379 requested changes

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/enums/DSProperties.java
> +			"\\server\\conf\\dslog.properties"), LocaleProperties("locale.properties",
enum の各要素は同じレベルであるべきかと思うので、１個めの `Properties` は `DSPropertiesController` で固定的に作った方が良さそう。そうすれば `DSPropertiesController#createTree` の Stream で `filter()` を省けるし。

パス区切りは `\\` でも良いですけど `/` 使った方がキレイに見えますよ^^

あと client 側のプロパティもほしいです。
その場合 Silverlight や WPF では client のプロパティをいじる意味がないので、表示非表示を切り替える手段を考える必要がありそうですが、それは一旦後回しでも良いかと。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +	private void Apply() {
Java ではメソッド名の先頭は小文字にすべきっすね。
先頭大文字だと C# とか Microsoft 文化っぽい。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +	private void onApplyandCloseButtonClick(final ActionEvent event) {
onApply**A**ndCloseButtonClick の誤り？

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +			manager.write();
`write()` メソッドに引数がないので `ConcurrentUtil.run(manager::write);` って書けます。
とはいえどっちのスタイルが好きとかあると思うので、しっくりくる書き方でよいです。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesView.fxml
> +						<ButtonBar buttonMinWidth="24.0" nodeOrientation="RIGHT_TO_LEFT" prefHeight="40.0" prefWidth="200.0">
画面に表示される並び順（追加ボタン→削除ボタン）と、FXML 上の定義順（削除ボタン→追加ボタン）の違いが気持ち悪いので、 あえて `ButtonBar` ではなく `HBox` 使っても良さそう。

`nodeOrientation="LEFT_TO_RIGHT"` した上でボタン群を左寄せできないかな、といろいろ試してみたけど㍉そうでしたorz
`Button` の `TranslateX `で調整する方法もあるけど、画面のリサイズとか考えると調整メンドクサそうだし、`HBox` 使った方が楽そうかなって。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +				.forEach(t -> root.getChildren().add(t));
これでスッキリ！
`Stream.of(DSProperties.values()).map(TreeItem::new).forEach(root.getChildren()::add);`（DSProperties の enum から `Properties` を削除する前提）

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		treeView.getSelectionModel().select(0);
せっかく `selectFirst()` があるので、そっちを使いましょう。
現場によっては CheckStyle とかで数値リテラル使ってると警告でアラートされるところもあるんですよねー。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSProperty.java
> +	private final BooleanProperty isEnable = new SimpleBooleanProperty(this, "isEnable");
変数名は `isXxx` の is はいりません。でないと getter メソッド名が `getIsXxx` とすることになるので。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSProperty.java
> +		statement.set((isEnable.get() ? "" : "#") + key.get() + "=" + value.get());
この処理 `onPropertyChenged()` でもやってるので、メソッドに切り出して名前つけてあげたい。処理にエイリアスを付けるイメージ。

あと `xxx.get()` よりか `getXxx()` 使ったほうが「ん？」ってならずに自然に読めそう。

2018-05-23 15:14 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSProperty.java
> +	public String toString() {
ここは `toString()` をオーバーライドするよりも `getStatement()` を実装すべき。
statement の値によって `DSProperty` インスタンスの生存期間中に `toString()` が返す値が変化することになるのが気持ち悪いなー、と。

2018-05-23 15:25 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/enums/DSProperties.java
> +			"\\server\\conf\\dslog.properties"), LocaleProperties("locale.properties",
あーclient 側のこと考えてませんでしたorz

2018-05-24 12:36 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +	private void onApplyandCloseButtonClick(final ActionEvent event) {
誤字ってますね。。

2018-05-24 12:37 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +	private void Apply() {
誤字多いっすね。。

2018-05-24 13:07 UTC, mizunaki commented
諸々対応しました。

2018-05-24 15:00 UTC, willard379 requested changes

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSProperty.java
> +	private final StringProperty statement = new SimpleStringProperty();
ここも `new SimpleStringProperty(this, "statement");` を入れてほしい。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSProperty.java
> +	public Boolean getEnable() {
ここは `isEnable()` にしてください。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSProperty.java
> +		this.enable.set(isEnable);
変数名は `enable`

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +	private final ObservableList<DSProperty> items = FXCollections.observableArrayList();
この ObservableList は不要では？
L97 で `setItems()` しなくても大丈夫ですよ。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		final TreeItem<String> root = new TreeItem<>("Properties");
なんだったら、 `root.setShowRoot(false);` ってやればツリーのルートノードは表示されなくなるので、コンストラクタに文字列を渡す必要もなくなるという。

もし client 側のプロパティも表示するようにするなら、

```
Properties
　├ Server
　│　└ なにがし.properties
　└ Studio
　　　└なにがし.properties
```

こんなカンジに階層が深くなるので、ますますルートノードが鬱陶しくなりそうですし。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		FXUtil.getStage(event).close();
`apply()` を別メソッドとして切り出しているので、同様にこれも `close()` メソッドとして切り出したいところ。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		ConcurrentUtil.run(() -> loadProperties(newValue.getValue()));
`newValue` が null のこともあるので、null チェックが必要。
画面上の操作としては、 Ctrl を押しながらアイテムを選択すると選択解除できる（＝nullが渡ってくる）。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +			manager.load(Paths.get(dsSetting.getExecutionPath(), DSProperties.of(properties).getPath()));
L117 でも `DSProperties.of(properties).getPath()` しているので、変数に代入して持っておきたい。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +			throw new IOException(properties + "が見つかりませんでした。");
IOException を catch した後に、新しい IOException を new して throw することに違和感。
new した例外のスタックトレースが表示されても原因調査の参考情報にはなり得ないので、意味があるのは `properties + "が見つかりませんでした。"` の部分ですよね？
であれば `DialogUtil.showWarningDialog(properties + "が見つかりませんでした。");` とかやってあげたほうがヨサゲ。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +			tableView.getItems().addAll(list);
`clear()` と `addAll()` をそれぞれ呼ばなくても `setAll()` で一度に洗い替えできますよ。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		manager = new DSPropertyManager();
`manager` をフィールド持ちする必要はないと思う。`onPropertyChanged()` で使いたいからだと思うけど、`DSProperties` のコンストラクタで `manager` を渡してあげて、`change` を捕捉する責任自体を `DSProperties` 側に閉じ込めてしまっても良さそう。

2018-05-24 15:00 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +					.map(p -> new DSProperty(p, this::onPropertyChanged)).collect(Collectors.toList());
`manager.load()` メソッドの戻り値でこの list を返してあげる方が自然な気がする。

2018-05-24 16:56 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +			throw new IOException(properties + "が見つかりませんでした。");
DialogUtil すっかり忘れてましたorz

2018-05-24 18:00 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		manager = new DSPropertyManager();
DSProperty のほうっすかね。（似たような名前で作ってしまったので紛らわしい・・orz）

2018-05-24 18:31 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		manager = new DSPropertyManager();
apply でmanager のwrite 使っているので、フィールド持ちは必要な気がします。（Controller と1:1 で使う）
change をDSProperty に持たせるのは、了解です。
試し案でやってみたので検討ください

2018-05-25 15:18 UTC, willard379 requested changes
今日の分。
明日また見る

2018-05-25 15:18 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		treeView.setShowRoot(false);
あーごめんなさい。これ SceneBuilder で設定したほうがよいですね。

2018-05-25 15:18 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		treeView.getSelectionModel().selectedItemProperty().addListener(this::onSelectedItemChanged);
Properties ダイアログを開いた直後、ツリーでは `dslog.properties` が選択状態になっているのに SplitPane の右側はなにも表示されてない。
`selectedItemProperty` にリスナーを貼った後に `selectFirst()` して `dslog.properties` のテーブルが表示されるようにするか、そもそも `selectFirst()` をやめて初期状態を未選択とするか。

無駄な処理を行うこともないので、後者が良いかな。

2018-05-25 15:18 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	private final String PATTERN = "(#)?[\\w.]*=[\\w\'#/:,-. ${}]*";
`DSProperty#parseProperty()` でも同じようなことやっているので、一本化したい。

この正規表現を `"(?<enable>#)?(?<key>\\S+)=(?<value>\\S*)"` として、`matcher.group("enable")` `matcher.group("key")` `matcher.group("value")` で取った値を `DSProperty`  のコンストラクタに渡してあげれば良さそう。

あとこれ static にできる。

2018-05-25 15:18 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +				.collect(Collectors.toList());
↑のコメントのようにやるなら、定数をこうして、

```java
private static final Pattern PATTERN = Pattern.compile("(?<enable>#)?(?<key>\\S+)=(?<value>\\S*)");
```

ここはこんなカンジにすればよさそう。

```java
return statement.stream().map(PATTERN::matcher).filter(Matcher::matches).map(m -> {
	final String enable = m.group("enable");
	final String key = m.group("key");
	final String value = m.group("value");
	return new DSProperty(enable, key, value, this);
}).collect(Collectors.toList());
```

2018-05-25 15:26 UTC, willard379 requested changes

2018-05-25 15:26 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		ConcurrentUtil.run(manager::save);
現状は `manager` がそのプロパティファイルの全プロパティを保持していて、`manager.save()` でそのプロパティをファイルに書き戻しているけど、`TreeView` から取り出した `DSProperty` が持っているデータを使ってファイルに書くようにすれば、manager をフィールドに保持する必要も、 `DSProperty`  でリスナーを貼りまくる必要もなくなると思う。

2018-05-25 15:33 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		ConcurrentUtil.run(manager::save);
そうすると `manager` がまったくマネージャの役割を演じなくなるので、各クラスの役割を考え直す必要がありそう。

2018-05-26 02:44 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		treeView.setShowRoot(false);
あ、そういえばそっちで設定できましたね。

2018-05-26 02:57 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		treeView.getSelectionModel().selectedItemProperty().addListener(this::onSelectedItemChanged);
初期状態未選択
Ctrl + Space でTreeの選択外れちゃうので、表示/非表示をTree の選択状態とバインドするようにしました。

2018-05-26 03:00 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +		treeView.getSelectionModel().selectedItemProperty().addListener(this::onSelectedItemChanged);
それプラスtree 未選択状態では[ApplyAndClose]を押しても何も起こらないようにしました

2018-05-26 04:05 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +				.collect(Collectors.toList());
まっちゃーべんりー

2018-05-26 08:36 UTC, willard379 requested changes

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/enums/DSProperties.java
> +	DSProperties(final String displayName, final String path) {
private でよさそう

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public List<DSProperty> load(final Path path) throws IOException {
`load()` メソッドを呼ばないと `DSPropertyManager` のインスタンスは実質無意味なので、コンストラクタと `load()` メソッドを分けずにコンストラクタのほうに処理を移したほうがよいと思う。

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public DSProperty addProperty(final String value) {
これシグニチャ見ただけだと引数になに渡したらよいか分からない、または key=value の value だけ渡せばよいのかと誤解を与えるので、`public DSProperty addProperty(final String key, final String value)` としたほうが良いと思う。

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public void deleteProperty(final String value) {
こっちも同様に、引数になに渡したらよいか分からない。
てゆーかこっちは key を渡すようにしたほうが自然だと思う。

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public void replace(final String target, final String newValue) {
これが一番引数になに渡したらよいか分からない。
`addProperty` と合体させる形で、すでにあれば更新、なければ追加っていう風にしたほうがよさそう。
名前も `setProperty` とかにして。

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public String generate() {
これは `save()` メソッドと統合したほうがよさそう。`generate` ってメソッド名からどんな処理なのか想像がつかないので。

2018-05-26 08:36 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/view/ds/DSPropertiesController.java
> +	public void initialize(final URL arg0, final ResourceBundle arg1) {
変数名 ``arg0` `arg1` はやめたい。

2018-05-29 14:06 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public void deleteProperty(final String value) {
現状key だと特定できないので、いったんプロパティ一行分丸っとのまま
「statement」に変更しときます。
このあとManager とかの動作変えるようならその時にまた直す感じで

2018-05-30 18:06 UTC, mizunaki commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +	public void replace(final String target, final String newValue) {
合体させる方法が思いつかないです。。

2018-05-30 18:19 UTC, mizunaki commented
一通りやってみました。

2018-06-02 07:34 UTC, willard379 requested changes

2018-06-02 07:34 UTC, willard379 commented on src/main/java/hoshisugi/rukoru/app/models/ds/DSPropertyManager.java
> +				new OutputStreamWriter(new FileOutputStream(path.toFile())))) {
`final BufferedWriter bw = Files.newBufferedWriter(path)` を使えばスッキリします。

2018-06-03 06:30 UTC, willard379 commented
僕の方で魔改造してみました！

* Studio のプロパティも表示するようにした
* プロパティファイルの品揃えをディレクトリから探すようにした
* モデルの構造を変更して DSPropertyManager を消した
* 初回保存時に .bak ファイルにバックアップを取るようにした
* DSEntry のボタンレイアウトを変更した
* ヘルプ開くボタンを追加した

2018-06-03 07:14 UTC, willard379 commented
![image](https://user-images.githubusercontent.com/1298724/40884128-38a915c8-6749-11e8-9c62-e972116d0f28.png)

2018-06-03 07:15 UTC, merged